version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    networks:
      my_network:
        ipv4_address: 172.20.0.6
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      my_network:
        ipv4_address: 172.20.0.8

volumes:
  db_data:

networks:
  my_network:
    name: honeypot_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
