version: '3.1'

services:
  ldap:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ldap_honeypot
    restart: always
    networks:
      - backend
      - frontend
    ports:
      - '389:389'
    volumes:
      - ./logs:/var/log/syslog-ng
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"

networks:
  frontend:
    internal: false
  backend:
    internal: true

